### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by imuli** [decentpatterns/website#20]
The LICENSE file holds CC0, but the actual files and website say CC-BY.

Which one is correct?

**Comment by bumbleblue** [comment]
Sorry for the confusion! The content of the site (patterns in the [library](https://github.com/decentpatterns/library)) should be CC0, the website (this repo) is CC-BY; at least that's my understanding.

**Comment by imuli** [comment]
Assuming that's correct, here's a PR! (The LICENSE file for the pattern library repo has CC0.)

**Comment by bumbleblue** [comment]
Thanks so much!
